[package]
license = "MIT"
description = "Navigate easily between your directories"
repository = "https://github.com/corepanic64/dirnav"
readme = "README.md"
name = "dirnav"
version = "0.1.1"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
